# Generated by Django 2.1.5 on 2020-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survay_01',
            name='question_01',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survay_02',
            name='question_02',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survay_04',
            name='question_04',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survay_05',
            name='question_05',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survay_06',
            name='question_06',
            field=models.IntegerField(),
        ),
    ]
